def obter_descricao_ocorrencia(codigo):
    ocorrencias = {
        "00": "Cobrança registrada",
        "01": "Cobrança recusada - instrução inválida",
        "02": "Entrada confirmada",
        "03": "Entrada rejeitada",
        "04": "Transferência de carteira/entrada",
        "05": "Transferência de carteira/baixa",
        "06": "Liquidação normal",
        "07": "Liquidação parcial",
        "08": "Baixa solicitada",
        "09": "Baixado automaticamente via arquivo",
        "10": "Baixado conforme instruções da agência",
        "11": "Em ser (só no retorno mensal)",
        "12": "Abatimento concedido",
        "13": "Abatimento cancelado",
        "14": "Vencimento alterado",
        "15": "Liquidação em cartório",
        "16": "Título pago em cheque - bloqueado",
        "17": "Liquidação após baixa ou título não registrado",
        "18": "Acerto de depositária",
        "19": "Confirmação recebimento instrução de protesto",
        "20": "Confirmação recebimento instrução sustação de protesto",
        "21": "Acerto do controle do participante",
        "22": "Título com pagamento cancelado",
        "23": "Entrada do título em cartório",
        "24": "Entrada rejeitada por CEP irregular",
        "25": "Confirmação recebimento instrução de alteração de dados",
        "26": "Debitado a conta corrente",
        "27": "Retirado da compensação por instrução",
        "28": "Débito não efetuado - falta de autorização",
        "29": "Débito não efetuado - saldo insuficiente",
        "30": "Débito não efetuado - conta inexistente",
        "31": "Liquidação normal - em trânsito",
        "32": "Rejeição do pagador - alega que faturamento é indevido",
        "33": "Instrução rejeitada - tipo de valor inválido",
        "34": "Instrução rejeitada - falta de comprovante prestação de serviço",
        "35": "Instrução rejeitada - não comprovado o pagamento do título",
        "36": "Instrução rejeitada - comprovante de prestação de serviços inválido",
        "40": "Estorno de pagamento",
        "41": "Estorno de pagamento - título em cartório",
        "42": "Estorno de pagamento – baixado",
        "43": "Estorno de pagamento – liquidado",
        "44": "Estorno de liquidação",
        "51": "Título DDA reconhecido pelo pagador",
        "52": "Título DDA não reconhecido pelo pagador",
        "53": "Título DDA recusado pela CIP",
        "AA": "Controle inválido",
        "AB": "Tipo de operação inválido",
        "AC": "Tipo de serviço inválido",
        "AD": "Forma de lançamento inválida",
        "AE": "Tipo/Número de inscrição inválido",
        "AF": "Código de convenio inválido",
        "AG": "Agência/conta corrente/DV inválido",
        "AH": "Nº sequencial do registro no lote inválido",
        "AI": "Código de segmento de detalhe inválido",
        "AJ": "Tipo de movimento inválido",
        "AK": "Código da câmara de compensação do banco favorecido/depositário inválido",
        "AL": "Código do banco favorecido ou depositário inválido",
        "AM": "Agência mantenedora da conta corrente do favorecido inválida",
        "AN": "Conta corrente/DV do favorecido inválido",
        "AO": "Nome do favorecido não informado",
        "AP": "Data lançamento inválido",
        "AQ": "Tipo/quantidade da moeda inválido",
        "AR": "Valor do lançamento inválido",
        "AS": "Aviso ao favorecido - identificação inválida",
        "AT": "Tipo/Número de inscrição do favorecido inválido",
        "AU": "Logradouro do favorecido não informado",
        "AV": "Nº do local do favorecido não informado",
        "AW": "Cidade do favorecido não informada",
        "AX": "CEP/complemento do favorecido inválido",
        "AY": "Sigla do estado do favorecido inválida",
        "AZ": "Código/Nome do banco depositário inválido",
        "BA": "Código/Nome da agência depositária inválido",
        "BB": "Seu número inválido",
        "BC": "Nosso número inválido",
        "BD": "Inclusão efetuada com sucesso",
        "BE": "Alteração efetuada com sucesso",
        "BF": "Exclusão efetuada com sucesso",
        "BG": "Agência/conta impedida legalmente",
        "BH": "Empresa não pagou salário",
    }
    
    codigo = codigo.strip() if codigo else ""
    return ocorrencias.get(codigo, f"Ocorrência {codigo} não mapeada")
